services:
  server:
    build:
      context: .
      target: dev
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
#    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - "./content:/src/content"
    x-develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
