---
baseURL: "/"
languageCode: "en-us"
title: "Your site name"
theme: "your-theme"
description: "A cool site!"

algolia:
  index: "services"
  key: "dad9958048bbb268af3435fdb8da2c52"
  appID: "L22VPDDY7O"
---